[package]
name = "csp_nif"
version = "0.1.0"
authors = []
edition = "2018"

[[bin]]
name = "csp"
path = "src/bin.rs"

[lib]
name = "csp_nif"
path = "src/lib.rs"
crate-type = ["rlib", "dylib"]

[dependencies]
rustler = "0.21.0"
lazy_static = "1.0"
