name: Elixir CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: '1.10.3' # Define the elixir version [required]
        otp-version: '22.2' # Define the OTP version [required]
    - name: Install Dependencies
      run: mix deps.get
    - name: Cache dialyzer plt
      uses: actions/cache@v1
      with:
        path: priv/plts
        key: ${{ runner.os }}-dialyzer-${{ hashFiles('**/mix.lock') }}-${{ hashFiles('**/mix.exs') }}
        restore-keys: ${{ runner.os }}-dialyzer-${{ hashFiles('**/mix.lock') }}-${{ hashFiles('**/mix.exs') }}
    - name: Run dialyzer
      run: mkdir -p priv/plts && mix dialyzer --halt-exit-status
    - name: Run Tests
      run: mix test
